name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DOC_PATH: target/doc

jobs:
  test:
    name: ${{ matrix.readable_os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          readable_os: Ubuntu
        - os: windows-latest
          readable_os: Windows
        - os: macos-latest
          readable_os: macOS
    steps:
    - uses: actions/checkout@v2
    - name: Clippy Checks
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy
    - name: Run Tests
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - uses: actions-rs/cargo@v1
      with:
        command: test
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build Documentation
      uses: actions-rs/cargo@v1
      with:
        command: doc
    - name: Copy Doc Index Page
      run: cp .github/pages/index.html ${{ env.DOC_PATH }}
    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DOC_PATH }}
        force_orphan: true
